name: first workflow
on: [push]

jobs:
  run_shell_commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: Run multiline command
        run : |
          node -v
          npm -v

  run_parallel_jobs: 
    runs-on: macos-latest
    steps:
      - name: View Software Version
        run: sw_vers

  run-dependant-jobs:
    runs-on: windows-latest
    needs: run_shell_commands
    steps:
      - name: echo a string
        run: Write-Output "Windows string"
      - name: Error Step
        run: doesnotexists